shop/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shop'

urlpatterns = [
    path('',  views.shop),
    path('login/',views.login,name='login')
    # path('create/',views.CreateProduct, name='create'),
    # path('edit/<pk>',views.CreateProduct)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopify/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('wp-admin/', admin.site.urls),
    path('admin/', include(('wp_admin.urls', 'wp_admin'), namespace='wp_admin')),
    path('shops/',include("shops.urls")),
    path("", include("shop.urls")),
]

shops/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'shops'

urlpatterns = [
    # path('',  views.shop),
    path('',views.index,name='index'),
    path('create/',views.CreateProduct, name='create'),
    path('edit/<int:id>/',views.EditProduct, name='edit'),
    path('product/<int:pk>/delete/', views.delete_product, name='delete')
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wp_admin/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'wp_admin'

urlpatterns = [
    # path('',  views.shop),
    path('',views.index,name='index'),
    path('create/',views.CreateProduct, name='create'),
    path('edit/<int:id>/',views.EditProduct, name='edit'),
    path('product/<int:pk>/delete/', views.delete_product, name='delete')
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models

# Create your models here.

class Customers(models.Model):
    name = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    emailid = models.CharField(max_length=1001)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    pname = models.CharField(max_length=100)
    pdesc = models.TextField(max_length=1000)
    stock = models.IntegerField()
    pprice = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    show = models.BooleanField(default=True)
    images = models.ImageField(upload_to='images/',null=True , blank=True)
    def __str__(self):
        return self.pname

shops/models.py
from django.db import models

# Create your models here.
class Products(models.Model):
    name = models.CharField(max_length=100)
    phone = models.IntegerField()
    cordinates =  models.IntegerField()
    state = models.CharField(max_length=100)
    adress = models.TextField()
    def __str__(self):
        return self.name

class Orders(models.Model):
    userid = models.IntegerField()
    orderid = models.IntegerField()
    orders = models.TextField()
    amount = models.IntegerField()
    location = models.TextField()
    top = models.CharField(max_length=100) #typeofpayment
    def __str__(self):
        return self.name

wp_admin/models.py
from django.db import models

shop/views.py
from django.shortcuts import render,redirect
from .models import Product,Customers
from .form import ProductForm,UsersLoginForm
from django.contrib import messages
# Create your views here.
def shop(request):
    products = Product.objects.all()  
    navbar = {'show_user_navbar': True}
    # if request.POST:
    #     frm = ProductForm(request.POST,request.FILES)
    #     print(request.FILES) 
    #     if frm.is_valid():
    #         frm.save()
    #         return redirect('create')
    # else:
    #     frm = ProductForm()
    print(products)  # Add this line to check if products are being fetched
    return render(request, "index.html", {'products': products, 'navbar': navbar})


def login(request):
    navbar = {'show_user_navbar': True}
    if request.method == 'POST':
        frm = UsersLoginForm(request.POST)
        print(request.POST)
        
        if frm.is_valid():
            try:
                # Corrected the get() method with keyword arguments
                user = Customers.objects.get(emailid=request.POST['emailid'])
                userpass = request.POST['password']
                if userpass == user.password:


                    print(user)
                    print('Login Successful')
                    return redirect('/')  # You can also use reverse('home') if you have a URL name
            except Customers.DoesNotExist:
                messages.error(request, 'User does not exist.')
            except Customers.MultipleObjectsReturned:
                messages.error(request, 'Multiple users found with this name.')
        else:
            messages.error(request, 'Invalid form submission.')
    else:
        frm = UsersLoginForm()
    return render(request, "login-user.html", {'navbar': navbar,'frm':frm})

def addtocart(request):
    if request.method ==  'POST':
        print(request.POST)

shops/views.py
from django.shortcuts import render
from django.shortcuts import render,redirect,get_object_or_404,HttpResponse
# from .. shop.models import Product
from .form import ProductForm,EditForm
from shop.models import Product
from django.contrib import messages
# Create your views here.

def index(request):
    products = Product.objects.all()  
    navbar = {'show_user_navbar': False}
    # if request.POST:
    #     frm = ProductForm(request.POST,request.FILES)
    #     print(request.FILES) 
    #     if frm.is_valid():
    #         frm.save()
    #         return redirect('create')
    # else:
    #     frm = ProductForm()
    print(products)  # Add this line to check if products are being fetched
    return render(request, "index-admin.html", {'products': products, 'navbar': navbar})

def CreateProduct(request):
    navbar = {'show_user_navbar': True}
    if request.POST:
        frm = ProductForm(request.POST,request.FILES)
        print(request.FILES) 
        if frm.is_valid():
            frm.save()
            return redirect('/')
    else:
        frm = ProductForm()
     # Add this line to check if products are being fetched
    return render(request, "create.html", {'navbar': navbar,'frm':frm})

def EditProduct(request, id):
    navbar = {'show_user_navbar': True}
    # Use get_object_or_404 for better error handling
    product = get_object_or_404(Product, id=id)
    
    if request.method == 'POST':
        frm = EditForm(request.POST,request.FILES, instance=product)
        if frm.is_valid():
            frm.save()  # Save changes to the database
            messages.success(request, 'Product details updated successfully!')
            return redirect('/')  # Redirect to a list view or another page
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        frm = EditForm(instance=product) 
    
    return render(request, "edit.html", {'navbar': navbar, 'frm': frm})

def delete_product(request, pk):
    """View to delete a product."""
    product = get_object_or_404(Product, pk=pk)

    # Ensure that deletion only happens on a POST request
    
    product.delete()
    return redirect('/')  # Redirect to the list view after deletion
    
    # If the request is GET, return a response or a confirmation message
    return HttpResponse("To delete the product, please confirm through a POST request.")  # Redirect to the list view or any other view after deletion

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shopify</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    {% if navbar.show_user_navbar %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary p-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Shopify</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {% else %}
      <nav class="navbar navbar-expand-lg bg-body-tertiary p-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Shopify Admin</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {% endif %}
      {% block content %}
    {% endblock content %}
    </body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
</html>

templates/create.html
{% extends 'base.html' %}
{% block content %}

<form method="post" action="{% url 'create' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ frm.as_p }}
    <button type="submit">Create</button>
</form>

{% endblock content %}

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Edit Product</title>
</head>
<body>
    <div class="container mt-5">
        <h2>Edit Product</h2>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <form method="POST" action="{% url 'wp_admin:edit' frm.instance.id %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ frm.as_p }} <!-- Ensure the form variable name matches the context variable from the view -->
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    </div>
</body>
</html>

templates/index-admin.html
{% extends 'base.html' %}

{% block content %}

<p>Number of products: {{ products|length }}</p>

<div class="row row-cols-1 row-cols-md-5 p-1 g-3">
    {% for product in products %}
    
    <div class="col">
        <div class="card h-100 w-70">
            <img src="media/{{product.images}}" class="img-fluid" style="width: 400px; height: 345px; object-fit: cover;" alt="Product Image">
            <div class="card-body">
                <h5 class="card-title">{{ product.pname }}</h5>
                <p class="card-text">{{ product.pdesc }}</p>
                <a href="{% url 'wp_admin:edit' product.id %}" class="btn btn-primary">{{product.pprice}}</a>
                <a href="#" onclick="confirmDelete('{{ product.id }}')" class="btn btn-danger">Delete</a>
            </div>
        </div>
    </div>

    {% empty %}
    <p>No products available.</p>
    {% endfor %}
</div>
<!-- product_list.html or wherever you display the delete button -->
<a href="#" onclick="confirmDelete('{{ product.id }}')">Delete</a>

<script>
function confirmDelete(productId) {
    if (confirm('Are you sure you want to delete this product?')) {
        // Redirect to the delete URL if the user confirms
        window.location.href = `product/${productId}/delete/`;  // Adjust this URL pattern if needed
    }
}
</script>

{% endblock content %}

templates/index.html
{% extends 'base.html' %}

{% block content %}

<p>Number of products: {{ products|length }}</p>

<div class="row row-cols-1 row-cols-md-5 p-1 g-3">
    {% for product in products %}
    {% if product.show %}
    <div class="col">
        <div class="card h-100 w-70">
            <img src="media/{{product.images}}" class="img-fluid" style="width: 400px; height: 345px; object-fit: cover;" alt="Product Image">
            <div class="card-body">
                <h5 class="card-title">{{ product.pname }}</h5>
                <p class="card-text">{{ product.pdesc }}</p>
                <a href="{% url 'wp_admin:edit' product.id %}" class="btn btn-primary">{{product.pprice}}</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% empty %}
    <p>No products available.</p>
    {% endfor %}
</div>

{% endblock content %}

templates/login-user.html
{% extends 'base.html' %}
{% block content %}

<section>
    <div class="container pt-5">
        <div class="container">
            <!-- Display messages -->
            {% if messages %}
                <div>
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} text-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        
            <!-- Your form or other content goes here -->
        </div>
        <div class="row">
            <form method="post"  action="{% url 'login' %}" enctype="multipart/form-data">
                <!-- Update URL pattern as necessary -->
                {% csrf_token %}
                {% if Error %}
                <p class="error mt-3">Invalid Email ID or Password</p>
                {% endif %}
                {% if Error1 %}
                <p class="error mt-3">Please Login First</p>
                {% endif %}
                <h1>Login</h1>
                <div class="mb-3">
                    {{ frm.emailid.label_tag }}
                    {{ frm.emailid }} <!-- Render email field with Bootstrap styling -->
                </div>
                <div class="mb-3">
                    {{ frm.password.label_tag }}
                    {{ frm.password }} <!-- Render password field with Bootstrap styling -->
                </div>
                <div class="row mt-4 p-2">
                    <input type="submit" class="btn btn-success p-3" style="border-radius: 9px;" value="Login">
                </div>
            </form>
        </div>
    </div>
</section>



{% endblock content %}